// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmpCsujvg3OKYt7rtXRDDXEWh_JaJQSuA',
    appId: '1:935942585475:web:b8f49bb9cdd69d579fefb6',
    messagingSenderId: '935942585475',
    projectId: 'flutter-firebase-dersler-c7357',
    authDomain: 'flutter-firebase-dersler-c7357.firebaseapp.com',
    storageBucket: 'flutter-firebase-dersler-c7357.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEKYlDL1suOdVA6XOjn-9ZuVuNrOhGk_k',
    appId: '1:935942585475:android:d25827d1018d59629fefb6',
    messagingSenderId: '935942585475',
    projectId: 'flutter-firebase-dersler-c7357',
    storageBucket: 'flutter-firebase-dersler-c7357.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsT7g2k6F_Nk-cqyrWkb-nZ6Ba6G7Kaog',
    appId: '1:935942585475:ios:e03353778766d1809fefb6',
    messagingSenderId: '935942585475',
    projectId: 'flutter-firebase-dersler-c7357',
    storageBucket: 'flutter-firebase-dersler-c7357.appspot.com',
    iosClientId: '935942585475-lshnaetkmi5hfqume5edbhv9tac8u0k2.apps.googleusercontent.com',
    iosBundleId: 'com.enesaydogdu.flutterFirebaseDersleri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsT7g2k6F_Nk-cqyrWkb-nZ6Ba6G7Kaog',
    appId: '1:935942585475:ios:e03353778766d1809fefb6',
    messagingSenderId: '935942585475',
    projectId: 'flutter-firebase-dersler-c7357',
    storageBucket: 'flutter-firebase-dersler-c7357.appspot.com',
    iosClientId: '935942585475-lshnaetkmi5hfqume5edbhv9tac8u0k2.apps.googleusercontent.com',
    iosBundleId: 'com.enesaydogdu.flutterFirebaseDersleri',
  );
}
